import sys, os
sys.path.insert(0, r'f:\Code\syndoriamiku.github.io')

content = ""
content += '"""\n'
content += 'name_scanner.py -- Rule-based Chinese person-name detector.\n'
content += 'No external dependencies. Imported by builder.py.\n'
content += '"""\n'
content += 'from __future__ import annotations\n'
content += 'import re\n'
content += 'from collections import defaultdict\n'
content += '\n'
content += 'try:\n'
content += '    import han_viet as _hv\n'
content += '    _HV_OK = True\n'
content += 'except ImportError:\n'
content += '    _hv = None\n'
content += '    _HV_OK = False\n'
content += '\n'
content += '_CJK = r"[\u4e00-\u9fff\u3400-\u4dbf]"\n'
content += '_CJK_RE = re.compile(_CJK)\n'
content += '\n'
content += 'def _is_cjk(ch):\n'
content += '    return "\u4e00" <= ch <= "\u9fff" or "\u3400" <= ch <= "\u4dbf"\n'
content += '\n'
content += 'def _all_cjk(s):\n'
content += '    return bool(s) and all(_is_cjk(c) for c in s)\n'
content += '\n'
content += 'def _ctx_snippet(text, start, end, pad=12):\n'
content += '    lo = max(0, start - pad)\n'
content += '    hi = min(len(text), end + pad)\n'
content += '    return text[lo:hi].replace("\\n", " ").strip()\n'
content += '\n'
content += '_PATTERNS = None\n'
content += '\n'
content += 'def _build_patterns():\n'
content += '    if not _HV_OK:\n'
content += '        return None\n'
content += '    cjk = _CJK\n'
content += '    verbs_all = sorted(_hv.VERB_SAY | _hv.VERB_ACT, key=len, reverse=True)\n'
content += '    verb_alt = "|".join(re.escape(v) for v in verbs_all)\n'
content += '    pat_verb = re.compile(f"({cjk}' + '{1,4})(?:{verb_alt})")\n'
content += '    prefix_alt = "|".join(\n'
content += '        re.escape(p) for p in sorted(_hv.NAME_CALL_PREFIXES, key=len, reverse=True))\n'
content += '    pat_call = re.compile(f"(?:{prefix_alt})({cjk}' + '{1,4})")\n'
content += '    title_alt = "|".join(\n'
content += '        re.escape(t) for t in sorted(_hv.TITLE_SUFFIXES, key=len, reverse=True))\n'
content += '    pat_title = re.compile(f"({cjk}' + '{1,3})(?:{title_alt})")\n'
content += '    pat_address = re.compile(\n'
content += '        r"(?:[\u300c\u300e\u201c]|(?<=[\u3002\uff01\uff1f\\n]))"\n'
content += '        r"([\u4e00-\u9fff\u3400-\u4dbf]{1,4})"\n'
content += '        r"(?=[\uff0c\uff01,!])",\n'
content += '        re.MULTILINE,\n'
content += '    )\n'
content += '    return pat_verb, pat_call, pat_title, pat_address\n'
content += '\n'
content += 'def _get_patterns():\n'
content += '    global _PATTERNS\n'
content += '    if _PATTERNS is None:\n'
content += '        _PATTERNS = _build_patterns()\n'
content += '    return _PATTERNS\n'
content += '\n'
content += 'class NameScanner:\n'
content += '    def __init__(self):\n'
content += '        if _HV_OK:\n'
content += '            self._single_surnames = _hv.SINGLE_SURNAMES\n'
content += '            self._double_surnames = _hv.DOUBLE_SURNAMES\n'
content += '            self._invalid = _hv.INVALID_NAME_CHARS\n'
content += '            self._stopwords = _hv.STOPWORD_TERMS\n'
content += '        else:\n'
content += '            self._single_surnames = set()\n'
content += '            self._double_surnames = []\n'
content += '            self._invalid = set()\n'
content += '            self._stopwords = set()\n'
content += '\n'
content += '    def scan(self, text, existing_glossary=None, max_results=200):\n'
content += '        if existing_glossary is None:\n'
content += '            existing_glossary = set()\n'
content += '        hits = defaultdict(lambda: {"signals": [], "contexts": []})\n'
content += '        patterns = _get_patterns()\n'
content += '        if patterns:\n'
content += '            pat_verb, pat_call, pat_title, pat_address = patterns\n'
content += '        else:\n'
content += '            pat_verb = pat_call = pat_title = pat_address = None\n'
content += '        self._signal_surname(text, hits)\n'
content += '        if pat_verb: self._signal_verb(text, pat_verb, hits)\n'
content += '        if pat_call: self._signal_call(text, pat_call, hits)\n'
content += '        if pat_title: self._signal_title(text, pat_title, hits)\n'
content += '        if pat_address: self._signal_address(text, pat_address, hits)\n'
content += '        results = self._build_results(hits, existing_glossary)\n'
content += '        results = self._dedup_substrings(results)\n'
content += '        results.sort(key=lambda x: (-x["confidence"], -x["count"], len(x["cn"])))\n'
content += '        return results[:max_results]\n'
content += '\n'
content += '    def _signal_surname(self, text, hits):\n'
content += '        invalid = self._invalid\n'
content += '        n = len(text)\n'
content += '        i = 0\n'
content += '        while i < n:\n'
content += '            ch = text[i]\n'
content += '            matched_ds = None\n'
content += '            for ds in self._double_surnames:\n'
content += '                if text[i:i + len(ds)] == ds:\n'
content += '                    matched_ds = ds\n'
content += '                    break\n'
content += '            if matched_ds:\n'
content += '                ds_len = len(matched_ds)\n'
content += '                for name_len in (ds_len + 1, ds_len + 2):\n'
content += '                    end = i + name_len\n'
content += '                    if end <= n:\n'
content += '                        cand = text[i:end]\n'
content += '                        if _all_cjk(cand) and not self._has_invalid_boundary(cand, invalid):\n'
content += '                            self._record(hits, cand, "surname", _ctx_snippet(text, i, end))\n'
content += '                i += 1\n'
content += '                continue\n'
content += '            if ch in self._single_surnames:\n'
content += '                for name_len in (2, 3):\n'
content += '                    end = i + name_len\n'
content += '                    if end <= n:\n'
content += '                        cand = text[i:end]\n'
content += '                        if _all_cjk(cand) and not self._has_invalid_boundary(cand, invalid):\n'
content += '                            self._record(hits, cand, "surname", _ctx_snippet(text, i, end))\n'
content += '                i += 1\n'
content += '                continue\n'
content += '            if ch == "\u963f" and i + 1 < n and _is_cjk(text[i + 1]):\n'
content += '                for name_len in (2, 3):\n'
content += '                    end = i + name_len\n'
content += '                    if end <= n:\n'
content += '                        cand = text[i:end]\n'
content += '                        if _all_cjk(cand) and not self._has_invalid_boundary(cand, invalid):\n'
content += '                            self._record(hits, cand, "surname", _ctx_snippet(text, i, end))\n'
content += '            i += 1\n'
content += '\n'
content += '    def _signal_verb(self, text, pat, hits):\n'
content += '        for m in pat.finditer(text):\n'
content += '            cand = self._strip_invalid(m.group(1), self._invalid)\n'
content += '            if self._valid_cand(cand):\n'
content += '                self._record(hits, cand, "verb_context", _ctx_snippet(text, m.start(), m.end()))\n'
content += '\n'
content += '    def _signal_call(self, text, pat, hits):\n'
content += '        for m in pat.finditer(text):\n'
content += '            cand = self._strip_invalid(m.group(1), self._invalid)\n'
content += '            if self._valid_cand(cand):\n'
content += '                ctx = _ctx_snippet(text, m.start(), m.end())\n'
content += '                self._record(hits, cand, "direct_call", ctx)\n'
content += '                self._record(hits, cand, "direct_call", ctx)\n'
content += '\n'
content += '    def _signal_title(self, text, pat, hits):\n'
content += '        for m in pat.finditer(text):\n'
content += '            cand = self._strip_invalid(m.group(1), self._invalid)\n'
content += '            if self._valid_cand(cand):\n'
content += '                self._record(hits, cand, "honorific", _ctx_snippet(text, m.start(), m.end()))\n'
content += '\n'
content += '    def _signal_address(self, text, pat, hits):\n'
content += '        for m in pat.finditer(text):\n'
content += '            cand = m.group(1).strip()\n'
content += '            cand = self._strip_invalid(cand, self._invalid)\n'
content += '            if self._valid_cand(cand) and len(cand) >= 2:\n'
content += '                self._record(hits, cand, "address", _ctx_snippet(text, m.start(), m.end()))\n'
content += '\n'
content += '    def _build_results(self, hits, existing_glossary):\n'
content += '        results = []\n'
content += '        for cn, data in hits.items():\n'
content += '            if cn in existing_glossary or cn in self._stopwords: continue\n'
content += '            if len(cn) < 2 or not _all_cjk(cn): continue\n'
content += '            if self._has_invalid_boundary(cn, self._invalid): continue\n'
content += '            signals = data["signals"]\n'
content += '            count = len(signals)\n'
content += '            unique_signals = list(dict.fromkeys(signals))\n'
content += '            conf = 0.0\n'
content += '            has_surname = "surname" in unique_signals\n'
content += '            has_verb    = "verb_context" in unique_signals\n'
content += '            has_call    = "direct_call" in unique_signals\n'
content += '            has_title   = "honorific" in unique_signals\n'
content += '            has_addr    = "address" in unique_signals\n'
content += '            if has_call:    conf += 0.65\n'
content += '            if has_surname: conf += 0.45\n'
content += '            if has_verb:    conf += min(0.40, 0.15 * signals.count("verb_context"))\n'
content += '            if has_title:   conf += 0.30\n'
content += '            if has_addr:    conf += 0.20\n'
content += '            if count >= 2:  conf += 0.10\n'
content += '            if count >= 5:  conf += 0.10\n'
content += '            if count >= 10: conf += 0.05\n'
content += '            conf = min(conf, 0.99)\n'
content += '            if count < 2 and not has_call and not has_surname: continue\n'
content += '            if conf < 0.25: continue\n'
content += '            seen = set(); uniq_ctx = []\n'
content += '            for c in data["contexts"]:\n'
content += '                if c not in seen:\n'
content += '                    seen.add(c); uniq_ctx.append(c)\n'
content += '                if len(uniq_ctx) >= 3: break\n'
content += '            results.append({"cn": cn, "confidence": conf, "count": count,\n'
content += '                "signals": unique_signals, "contexts": uniq_ctx,\n'
content += '                "suggested_vi": self._suggest_vi(cn)})\n'
content += '        return results\n'
content += '\n'
content += '    def _dedup_substrings(self, results):\n'
content += '        rs = sorted(results, key=lambda x: -len(x["cn"]))\n'
content += '        sup = set()\n'
content += '        for item in rs:\n'
content += '            if item["cn"] in sup: continue\n'
content += '            for s in rs:\n'
content += '                if len(s["cn"]) < len(item["cn"]) and s["cn"] in item["cn"]:\n'
content += '                    if s["count"] <= item["count"] * 1.2:\n'
content += '                        sup.add(s["cn"])\n'
content += '        return [x for x in rs if x["cn"] not in sup]\n'
content += '\n'
content += '    @staticmethod\n'
content += '    def _record(hits, cn, signal, ctx):\n'
content += '        hits[cn]["signals"].append(signal)\n'
content += '        if len(hits[cn]["contexts"]) < 5: hits[cn]["contexts"].append(ctx)\n'
content += '\n'
content += '    @staticmethod\n'
content += '    def _has_invalid_boundary(cn, invalid):\n'
content += '        return (cn[0] in invalid) or (cn[-1] in invalid)\n'
content += '\n'
content += '    @staticmethod\n'
content += '    def _strip_invalid(s, invalid):\n'
content += '        while s and s[0] in invalid: s = s[1:]\n'
content += '        while s and s[-1] in invalid: s = s[:-1]\n'
content += '        return s\n'
content += '\n'
content += '    @staticmethod\n'
content += '    def _valid_cand(cn):\n'
content += '        return bool(cn) and len(cn) >= 1 and _all_cjk(cn)\n'
content += '\n'
content += '    @staticmethod\n'
content += '    def _suggest_vi(cn):\n'
content += '        return _hv.han_viet_name(cn) if _HV_OK else ""\n'
content += '\n'
content += 'if __name__ == "__main__":\n'
content += '    sample = (\n'
content += '        "\u6797\u9298\u770b\u7740\u773c\u524d\u7684\u5c11\u5973\uff0c\u5fc3\u4e2d\u5fae\u5fae\u4e00\u52a8\u3002\\n"\n'
content += '        "\u201c\u88f4\u6e58\u541b\uff0c\u4f60\u6765\u4e86\u3002\u201d\u5c11\u5973\u5fae\u7b11\u9053\u3002\\n"\n'
content += '        "\u6797\u9298\u70b9\u5934\uff0c\u8d70\u5411\u90a3\u540d\u53eb\u505a\u963f\u5b9d\u7684\u5c11\u5e74\u3002\\n"\n'
content += '        "\u6b27\u9633\u96ea\u5927\u4eba\u76b1\u4e86\u76b1\u7709\uff0c\u51b7\u58f0\u9053\uff1a\u201c\u4f60\u4eec\u4e24\u4e2a\uff0c\u8fc7\u6765\u3002\u201d\\n"\n'
content += '        "\u6797\u9298\u8bf4\u9053\uff1a\u201c\u662f\u3002\u201d\u4ed6\u671d\u6b27\u9633\u96ea\u884c\u793c\u3002\\n"\n'
content += '        "\u88f4\u6e58\u541b\u7b11\u9053\uff1a\u201c\u4ed6\u662f\u6797\u9298\uff0c\u6211\u7684\u5e08\u5144\u3002\u201d\\n"\n'
content += '        "\u72ec\u5b64\u7682\u4f4e\u5934\u6c89\u601d\uff0c\u968f\u5373\u62ac\u5934\u671b\u7740\u8fdc\u5904\u3002\\n"\n'
content += '    )\n'
content += '    scanner = NameScanner()\n'
content += '    res = scanner.scan(sample, existing_glossary=set())\n'
content += '    print(f"Found {len(res)} candidates:")\n'
content += '    for r in res:\n'
content += '        sigs = "+".join(r["signals"])\n'
content += "        print(f\"  {r['cn']:6s}  conf={r['confidence']:.2f}  n={r['count']:2d}  [{sigs}]  -> {r['suggested_vi']}\")\n"
content += "        if r['contexts']: print(f\"         ctx: {r['contexts'][0]!r}\")\n"

with open(r'f:\Code\syndoriamiku.github.io\name_scanner.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('WRITE_OK')
